#!/usr/bin/env python3
"""memory - persistent, searchable memory for AI coding agents (project + global).

Store small, verified facts once; later recall only the few that matter, instead of
re-discovering them or loading a big notes file every session.

  memory.py add "text" [--kind K] [--tags a,b] [--files f1,f2] [--global]
  memory.py recall "query" [-n 5]      best matches from project + global memory
  memory.py brief [-n 12]              short session-start digest (prefs, gotchas, commands, recent)
  memory.py list [--kind K] [--global | --project] [-n 30]
  memory.py stale                      entries whose referenced files changed or vanished
  memory.py update ID "new text"       replace an entry's text (keeps id, refreshes file hashes)
  memory.py forget ID [ID ...]         delete entries
  memory.py export                     Markdown dump for humans / tools without Python

Kinds: fact, fix, decision, pref, gotcha, cmd, api, todo  (default: fact)
Project memory: <repo>/.codemap/memory.jsonl  (local by default; share deliberately)
Global memory:  ~/.agents/memory.jsonl        (override dir with $AGENT_MEMORY_HOME)
Python 3.8+, standard library only.
"""

import argparse
import hashlib
import json
import math
import os
import re
import subprocess
import sys
import time
from contextlib import contextmanager
from pathlib import Path
import tempfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../token-saver/scripts")))
from ts_io import redact, safe_path, secret_path

KINDS = ("fact", "fix", "decision", "pref", "gotcha", "cmd", "api", "todo")
BRIEF_ORDER = {"pref": 0, "gotcha": 1, "cmd": 2, "decision": 3, "todo": 4, "fix": 5, "api": 6, "fact": 7}
MAX_TEXT = 500
GITIGNORE = ("# generated by repomap: keep NOTES.md in git; memory stays local by default\n"
             "*\n!.gitignore\n!NOTES.md\n")
STOP = set("""a an the of to in on for and or is are was were be been with by at as it its this that
these those from not no use used using when then than into via do does did has have had can
should must will would may might if else so but also just only very""".split())


# ---------------------------------------------------------------- storage

def repo_root():
    try:
        r = subprocess.run(["git", "rev-parse", "--show-toplevel"], stdout=subprocess.PIPE,
                           stderr=subprocess.DEVNULL, timeout=20)
        if r.returncode == 0:
            return r.stdout.decode("utf-8", "replace").strip()
    except (OSError, subprocess.SubprocessError):
        pass
    return os.getcwd()


def global_path():
    base = os.environ.get("AGENT_MEMORY_HOME") or os.path.join(os.path.expanduser("~"), ".agents")
    return os.path.join(base, "memory.jsonl")


def project_path(root):
    return os.path.join(root, ".codemap", "memory.jsonl")


def ensure_codemap(root):
    d = str(safe_path(root, ".codemap"))
    os.makedirs(d, exist_ok=True)
    gi = os.path.join(d, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write(GITIGNORE)
        return


def load(path, strict=False):
    out = []
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        entry = json.loads(line)
                        if (not isinstance(entry, dict) or not isinstance(entry.get("id"), str)
                                or not isinstance(entry.get("text"), str)
                                or not isinstance(entry.get("files", {}), dict)
                                or not isinstance(entry.get("tags", []), list)):
                            raise ValueError("invalid memory entry")
                        out.append(entry)
                    except ValueError:
                        if strict:
                            raise ValueError("memory file contains invalid entries; repair it before writing")
    except OSError:
        pass
    return out


def save(path, entries):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".memory-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            for e in entries:
                fh.write(json.dumps(e, ensure_ascii=False, separators=(",", ":")) + "\n")
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def file_hash(root, rel):
    try:
        if secret_path(rel):
            return None
        path = safe_path(root, rel)
        if path.stat().st_size > 5_000_000:
            return None
        with open(path, "rb") as fh:
            return hashlib.sha1(fh.read(5_000_001)).hexdigest()[:10]
    except (OSError, ValueError):
        return None


def norm_rel(root, p):
    p = p.strip()
    full = p if os.path.isabs(p) else os.path.join(os.getcwd(), p)
    rel = os.path.relpath(full, root).replace(os.sep, "/")
    safe_path(root, rel)
    if secret_path(rel):
        raise ValueError("credential files cannot be linked to memory")
    return rel


# ---------------------------------------------------------------- search

def tokens(s):
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", s or "")
    return [w for w in re.findall(r"[^\W_]+", s.lower()) if len(w) > 1 and w not in STOP]


def doc_text(e):
    return " ".join([e.get("text", ""), " ".join(e.get("tags", [])), e.get("kind", ""),
                     " ".join(e.get("files", {}).keys())])


def bm25(entries, query, k1=1.2, b=0.75):
    docs = [tokens(doc_text(e)) for e in entries]
    n = len(docs)
    if not n:
        return []
    avg = sum(len(d) for d in docs) / n or 1.0
    df = {}
    for d in docs:
        for t in set(d):
            df[t] = df.get(t, 0) + 1
    idf = {t: math.log(1 + (n - c + 0.5) / (c + 0.5)) for t, c in df.items()}
    q = tokens(query)
    # prefix matches (auth ~ authentication) at a discount
    expanded = {}
    for t in q:
        expanded[t] = max(expanded.get(t, 0), 1.0)
        if len(t) >= 4:
            for v in df:
                if v != t and len(v) >= 4 and (v.startswith(t) or t.startswith(v)):
                    expanded[v] = max(expanded.get(v, 0), 0.6)
    scores = []
    for e, d in zip(entries, docs):
        tf = {}
        for t in d:
            tf[t] = tf.get(t, 0) + 1
        s = 0.0
        for t, w in expanded.items():
            f = tf.get(t)
            if f:
                s += w * idf[t] * f * (k1 + 1) / (f + k1 * (1 - b + b * len(d) / avg))
        if s > 0:
            scores.append((s, e))
    scores.sort(key=lambda x: -x[0])
    return scores


def jaccard(a, b):
    a, b = set(tokens(a)), set(tokens(b))
    return len(a & b) / len(a | b) if a and b else 0.0


# ---------------------------------------------------------------- display

def stale_info(root, e):
    """'' if fine, else a short note about changed/missing files."""
    if e.get("_scope") != "project" or not e.get("files"):
        return ""
    changed = []
    for rel, h in e["files"].items():
        cur = file_hash(root, rel)
        if cur is None:
            changed.append(rel + " (gone)")
        elif cur != h:
            changed.append(rel + " (changed)")
    return ("  !! verify: " + ", ".join(changed)) if changed else ""


def fmt(root, e, width=300):
    text = e.get("text", "")
    if len(text) > width:
        text = text[:width] + "…"
    tags = (" #" + " #".join(e["tags"])) if e.get("tags") else ""
    files = (" | files: " + ", ".join(e["files"])) if e.get("files") else ""
    return "%s [%s] %s%s%s%s" % (e["id"], e.get("kind", "fact"), text, tags, files, stale_info(root, e))


# ---------------------------------------------------------------- commands

def all_entries(root, scopes=("project", "global")):
    out = []
    if "project" in scopes:
        for e in load(project_path(root)):
            e["_scope"] = "project"
            out.append(e)
    if "global" in scopes:
        for e in load(global_path()):
            e["_scope"] = "global"
            out.append(e)
    return out


def strip(entries):
    return [{k: v for k, v in e.items() if not k.startswith("_")} for e in entries]


def next_id(entries, prefix):
    nums = [int(e["id"][1:]) for e in entries if str(e.get("id", ""))[1:].isdigit()]
    return "%s%d" % (prefix, (max(nums) + 1) if nums else 1)


def cmd_add(root, args):
    text = " ".join(args.text.split())
    if not text:
        print("memory: empty text")
        return 2
    if redact(text) != text:
        raise ValueError("do not store credentials in memory; store a reference to their location")
    scope = "global" if args.glob else "project"
    path = global_path() if args.glob else project_path(root)
    if not args.glob:
        ensure_codemap(root)
    entries = load(path)
    files = {}
    if args.files and not args.glob:
        for p in args.files.split(","):
            if not p.strip():
                continue
            rel = norm_rel(root, p)
            h = file_hash(root, rel)
            if h is None:
                print("memory: warning, file not found: %s (stored without hash)" % rel)
                h = "-"
            files[rel] = h
    tags = [t.strip().lower() for t in (args.tags or "").split(",") if t.strip()]
    today = time.strftime("%Y-%m-%d")
    for e in entries:  # near-duplicate -> update instead of piling up
        if e.get("kind") == args.kind and jaccard(e.get("text", ""), text) >= 0.7:
            e["text"] = text
            e["tags"] = sorted(set(e.get("tags", [])) | set(tags))
            e.setdefault("files", {}).update(files)
            e["updated"] = today
            save(path, entries)
            print("memory: updated %s (a similar %s entry existed)" % (e["id"], scope))
            return 0
    e = {"id": next_id(entries, "g" if args.glob else "p"), "kind": args.kind, "text": text,
         "date": today}
    if tags:
        e["tags"] = tags
    if files:
        e["files"] = files
    entries.append(e)
    save(path, entries)
    note = "  (long: keep entries to 1-2 sentences)" if len(text) > MAX_TEXT else ""
    print("memory: saved %s (%s)%s" % (e["id"], scope, note))
    return 0


def cmd_recall(root, args):
    entries = all_entries(root)
    if args.kind:
        entries = [e for e in entries if e.get("kind") == args.kind]
    hits = bm25(entries, args.query)
    if not hits:
        print("memory: nothing matches %r (%d entries searched)" % (args.query, len(entries)))
        return 1
    for _, e in hits[:args.n]:
        print(fmt(root, e))
    if len(hits) > args.n:
        print("… %d more matches (-n to show more)" % (len(hits) - args.n))
    return 0


def cmd_brief(root, args):
    entries = all_entries(root)
    if not entries:
        print("memory: empty. Save verified, reusable facts with `memory.py add \"...\" --kind gotcha|cmd|pref|fix|decision`")
        return 0
    def key(e):
        return (BRIEF_ORDER.get(e.get("kind"), 9), e.get("_scope") != "global",
                -int(re.sub(r"\D", "", e.get("updated") or e.get("date") or "0") or 0))
    ranked = sorted(entries, key=key)
    nproj = sum(1 for e in entries if e["_scope"] == "project")
    print("memory: %d project + %d global entries; top %d below. `recall QUERY` for task-specific ones."
          % (nproj, len(entries) - nproj, min(args.n, len(entries))))
    budget = args.chars
    for e in ranked[:args.n]:
        line = fmt(root, e, width=200)
        if budget - len(line) < 0:
            break
        budget -= len(line)
        print(line)
    return 0


def cmd_list(root, args):
    scopes = ("global",) if args.glob else ("project",) if args.project else ("project", "global")
    entries = all_entries(root, scopes)
    if args.kind:
        entries = [e for e in entries if e.get("kind") == args.kind]
    entries.sort(key=lambda e: e.get("updated") or e.get("date") or "", reverse=True)
    for e in entries[:args.n]:
        print(fmt(root, e, width=160))
    if len(entries) > args.n:
        print("… %d more" % (len(entries) - args.n))
    if not entries:
        print("memory: no entries")
    return 0


def cmd_stale(root, args):
    found = 0
    for e in all_entries(root, ("project",)):
        info = stale_info(root, e)
        if info:
            found += 1
            print(fmt(root, e, width=160))
    print("memory: %d stale entr%s -> re-verify, then `update ID \"text\"` or `forget ID`"
          % (found, "y" if found == 1 else "ies") if found else "memory: nothing stale")
    return 0


def edit_entries(root, ids, fn):
    done = set()
    for path, prefix in ((project_path(root), "p"), (global_path(), "g")):
        mine = [i for i in ids if i.startswith(prefix)]
        if not mine:
            continue
        entries = load(path)
        new = []
        for e in entries:
            if e.get("id") in mine:
                done.add(e["id"])
                e = fn(e)
                if e is None:
                    continue
            new.append(e)
        if done & set(mine):
            save(path, new)
    return done


def cmd_update(root, args):
    text = " ".join(args.text.split())
    if not text or redact(text) != text:
        raise ValueError("memory must be nonempty and contain no detected credentials")

    def upd(e):
        e["text"] = text
        e["updated"] = time.strftime("%Y-%m-%d")
        if e.get("files"):
            e["files"] = {rel: (file_hash(root, rel) or "-") for rel in e["files"]}
        return e
    done = edit_entries(root, [args.id], upd)
    print("memory: updated %s" % args.id if done else "memory: no entry %s" % args.id)
    return 0 if done else 1


def cmd_forget(root, args):
    done = edit_entries(root, args.ids, lambda e: None)
    missing = [i for i in args.ids if i not in done]
    print("memory: removed %s%s" % (" ".join(sorted(done)) or "nothing",
                                    ("; not found: " + " ".join(missing)) if missing else ""))
    return 0 if done else 1


def cmd_export(root, args):
    for scope in ("project", "global"):
        entries = all_entries(root, (scope,))
        if not entries:
            continue
        print("# %s memory\n" % scope.capitalize())
        for kind in sorted({e.get("kind", "fact") for e in entries}, key=lambda k: BRIEF_ORDER.get(k, 9)):
            print("## %s" % kind)
            for e in entries:
                if e.get("kind", "fact") == kind:
                    extra = (" (files: %s)" % ", ".join(e["files"])) if e.get("files") else ""
                    print("- %s: %s%s" % (e["id"], e.get("text", ""), extra))
            print()
    return 0


@contextmanager
def write_lock(path):
    directory = Path(path).parent
    directory.mkdir(parents=True, exist_ok=True)
    lock = safe_path(directory, Path(path).name + ".lock")
    deadline = time.monotonic() + 5
    while True:
        try:
            fd = os.open(str(lock), os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
            os.close(fd)
            break
        except FileExistsError:
            if time.monotonic() >= deadline:
                raise ValueError("memory is being written; retry after the writer completes")
            time.sleep(0.05)
    try:
        yield
    finally:
        lock.unlink()


def main(argv=None):
    ap = argparse.ArgumentParser(prog="memory.py", description=__doc__.split("\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", help="repository root (default: git top-level or cwd)")
    sub = ap.add_subparsers(dest="cmd")
    a = sub.add_parser("add", help="save a memory")
    a.add_argument("text")
    a.add_argument("--kind", default="fact", choices=KINDS)
    a.add_argument("--tags", default="")
    a.add_argument("--files", default="", help="comma list; hashed so changes are flagged later")
    a.add_argument("--global", dest="glob", action="store_true", help="cross-project memory")
    r = sub.add_parser("recall", help="search memories")
    r.add_argument("query")
    r.add_argument("-n", type=int, default=5)
    r.add_argument("--kind", choices=KINDS)
    b = sub.add_parser("brief", help="session-start digest")
    b.add_argument("-n", type=int, default=12)
    b.add_argument("--chars", type=int, default=2000, help="output budget in characters")
    l = sub.add_parser("list", help="list memories")
    l.add_argument("--kind", choices=KINDS)
    l.add_argument("--global", dest="glob", action="store_true")
    l.add_argument("--project", action="store_true")
    l.add_argument("-n", type=int, default=30)
    sub.add_parser("stale", help="entries whose files changed")
    u = sub.add_parser("update", help="replace an entry's text")
    u.add_argument("id")
    u.add_argument("text")
    f = sub.add_parser("forget", help="delete entries")
    f.add_argument("ids", nargs="+")
    sub.add_parser("export", help="markdown dump")
    args = ap.parse_args(argv)
    root = os.path.abspath(args.root) if args.root else repo_root()
    handlers = {"add": cmd_add, "recall": cmd_recall, "brief": cmd_brief, "list": cmd_list,
                "stale": cmd_stale, "update": cmd_update, "forget": cmd_forget, "export": cmd_export}
    if args.cmd not in handlers:
        ap.print_help()
        return 2
    if hasattr(args, "n") and args.n < 1 or hasattr(args, "chars") and args.chars < 1:
        ap.error("output limits must be positive")
    safe_path(root, ".codemap/memory.jsonl")
    global_file = Path(global_path())
    safe_path(global_file.parent, global_file.name)
    if args.cmd in ("add", "update", "forget"):
        # Always take locks in the same order to prevent lost updates/deadlocks.
        with write_lock(project_path(root)), write_lock(global_path()):
            load(project_path(root), strict=True)
            load(global_path(), strict=True)
            return handlers[args.cmd](root, args)
    return handlers[args.cmd](root, args)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except BrokenPipeError:
        sys.exit(0)
    except (OSError, ValueError) as error:
        print("memory: " + str(error), file=sys.stderr)
        sys.exit(2)
