#!/usr/bin/env python3
"""repomap - compact, incremental code map for AI coding agents.

Replaces "explore the repo again" with a small index: every file, its symbols
and their line numbers. Only files whose size/mtime changed are re-parsed.

Usage (run inside the repo, or pass --root DIR):
  repomap.py build              refresh .codemap/MAP.md, print a one-line summary
  repomap.py status             files added / modified / removed since last build
  repomap.py find REGEX [-n N]  where is a symbol defined -> path:line kind name
  repomap.py outline FILE...    symbols of a file with line numbers (no full read)
  repomap.py show PREFIX        the map lines for one directory / file prefix

Python 3.8+, standard library only.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time

VERSION = 1
MAP_DIR = ".codemap"
MAX_PARSE_BYTES = 1_000_000      # bigger files are listed but not parsed
MAX_SYMS_PER_FILE = 40           # in MAP.md; `outline` shows everything
MAX_CHILDREN = 20                # members shown per class in MAP.md
MAX_OTHER_NAMES = 12             # non-source file names listed per directory
INDEX_MAX_ENTRIES = 40           # directory index rows
MAX_WALK_FILES = 20000           # safety cap when the folder is not a git repo

GITIGNORE = ("# generated by repomap: keep NOTES.md and memory.jsonl in git, ignore the rest\n"
             "*\n!.gitignore\n!NOTES.md\n!memory.jsonl\n")

# ---------------------------------------------------------------- filtering

SKIP_DIRS_ALWAYS = {
    "node_modules", "vendor", "dist", ".codemap", "__pycache__", ".next", ".nuxt",
    ".svelte-kit", "coverage", "Pods", ".yarn", ".pnpm-store", "bower_components",
    ".git", ".hg", ".svn",
}
SKIP_DIRS_WALK = SKIP_DIRS_ALWAYS | {
    "build", "out", "target", "venv", ".venv", "env", ".env", ".tox", ".cache",
    ".gradle", ".idea", ".vscode", "bin", "obj", "DerivedData", ".terraform",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", "site-packages", ".dart_tool",
    ".turbo", ".parcel-cache", ".expo", "storybook-static", ".angular", "tmp",
}
SKIP_FILES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb", "bun.lock",
    "Cargo.lock", "poetry.lock", "Pipfile.lock", "composer.lock", "Gemfile.lock",
    "go.sum", "mix.lock", "pubspec.lock", "Podfile.lock", "packages.lock.json",
    "flake.lock", "uv.lock", ".DS_Store", "Thumbs.db",
}
SKIP_SUFFIXES = (
    ".min.js", ".min.css", ".min.mjs", ".map", ".snap", ".lock", ".pb.go", "_pb2.py",
    "_pb2_grpc.py", ".pb.cc", ".pb.h", ".g.dart", ".freezed.dart", ".generated.ts",
    ".generated.cs", ".designer.cs", ".bundle.js", ".chunk.js",
)
ASSET_EXT = {
    "png", "jpg", "jpeg", "gif", "bmp", "ico", "icns", "webp", "avif", "svg", "tif",
    "tiff", "psd", "ttf", "otf", "woff", "woff2", "eot", "mp3", "wav", "ogg", "flac",
    "mp4", "mov", "avi", "webm", "mkv", "zip", "gz", "tgz", "bz2", "xz", "7z", "rar",
    "tar", "jar", "war", "class", "exe", "dll", "so", "dylib", "a", "o", "obj", "lib",
    "wasm", "pyc", "pyo", "db", "sqlite", "sqlite3", "pdf", "doc", "docx", "xls",
    "xlsx", "ppt", "pptx", "bin", "dat", "pkl", "npy", "npz", "pt", "onnx", "h5",
    "parquet", "avro", "keystore", "p12", "pem", "der", "crt", "ds_store",
}

# ---------------------------------------------------------------- languages
# Each entry: (kind, regex with group "n", is_container, member_only)
# member_only patterns fire only directly inside a container (class body etc).

KW = {
    "if", "for", "while", "switch", "catch", "return", "else", "elif", "do", "try",
    "with", "new", "delete", "throw", "await", "yield", "case", "sizeof", "typeof",
    "function", "super", "this", "import", "require", "when", "match", "select",
    "using", "lock", "foreach", "until", "unless", "defer", "go",
}


def _c(p, flags=0):
    return re.compile(p, flags)


MOD_JAVA = r"(?:(?:public|private|protected|internal|static|final|abstract|sealed|non-sealed|strictfp|synchronized|native|default|virtual|override|async|extern|unsafe|new|readonly|partial|transient|volatile|open|inline|const|constexpr|explicit|friend|mutable)\s+)*"

JS = [
    ("class", _c(r"^\s*(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:abstract\s+)?class\s+(?P<n>[\w$]+)"), True, False),
    ("iface", _c(r"^\s*(?:export\s+)?(?:declare\s+)?interface\s+(?P<n>[\w$]+)"), False, False),
    ("type", _c(r"^\s*(?:export\s+)?(?:declare\s+)?type\s+(?P<n>[\w$]+)\s*(?:<.*?>)?\s*="), False, False),
    ("enum", _c(r"^\s*(?:export\s+)?(?:declare\s+)?(?:const\s+)?enum\s+(?P<n>[\w$]+)"), False, False),
    ("ns", _c(r"^\s*(?:export\s+)?(?:declare\s+)?(?:namespace|module)\s+(?P<n>[\w$.]+)\s*\{"), True, False),
    ("fn", _c(r"^\s*(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:async\s+)?function\s*\*?\s*(?P<n>[\w$]+)"), False, False),
    ("fn", _c(r"^\s*(?:export\s+)?(?:const|let|var)\s+(?P<n>[\w$]+)\s*(?::[^=]+)?=\s*(?:async\s+)?(?:function\b|\([^)]*\)\s*(?::[^=]+?)?=>|[\w$]+\s*=>|\(\s*$|<[^>]*>\s*\()"), False, False),
    ("fn", _c(r"^\s*(?P<n>(?:[\w$]+\.)+[\w$]+)\s*=\s*(?:async\s+)?(?:function\b|\([^)]*\)\s*=>|[\w$]+\s*=>)"), False, False),
    ("const", _c(r"^export\s+(?:const|let|var)\s+(?P<n>[\w$]+)"), False, False),
    ("method", _c(r"^\s+(?:(?:public|private|protected|static|readonly|abstract|override|async|declare|get|set)\s+)*\*?#?(?P<n>[\w$]+)\s*(?:<[^>]*>)?\s*\([^;]*$"), False, True),
    ("method", _c(r"^\s+(?:(?:public|private|protected|static|readonly)\s+)*#?(?P<n>[\w$]+)\s*(?::[^=]+)?=\s*(?:async\s+)?(?:\([^)]*\)|[\w$]+)\s*(?::[^=]+?)?=>"), False, True),
]

PY = [
    ("class", _c(r"^\s*class\s+(?P<n>\w+)"), True, False),
    ("fn", _c(r"^\s*(?:async\s+)?def\s+(?P<n>\w+)"), False, False),
]

GO = [
    ("fn", _c(r"^func\s+\((?P<recv>[^)]*)\)\s*(?P<n>\w+)"), False, False),
    ("fn", _c(r"^func\s+(?P<n>\w+)"), False, False),
    ("type", _c(r"^type\s+(?P<n>\w+)"), False, False),
    ("type", _c(r"^\s+(?P<n>[A-Z]\w*)\s+(?:struct|interface)\s*\{"), False, False),
]

RUST_VIS = r"(?:pub(?:\([^)]*\))?\s+)?"
RUST = [
    ("fn", _c(r"^\s*" + RUST_VIS + r"(?:default\s+)?(?:const\s+)?(?:async\s+)?(?:unsafe\s+)?(?:extern\s+\"[^\"]*\"\s+)?fn\s+(?P<n>\w+)"), False, False),
    ("struct", _c(r"^\s*" + RUST_VIS + r"struct\s+(?P<n>\w+)"), False, False),
    ("enum", _c(r"^\s*" + RUST_VIS + r"enum\s+(?P<n>\w+)"), False, False),
    ("union", _c(r"^\s*" + RUST_VIS + r"union\s+(?P<n>\w+)"), False, False),
    ("trait", _c(r"^\s*" + RUST_VIS + r"(?:unsafe\s+)?trait\s+(?P<n>\w+)"), True, False),
    ("type", _c(r"^\s*" + RUST_VIS + r"type\s+(?P<n>\w+)"), False, False),
    ("impl", _c(r"^\s*(?:unsafe\s+)?impl(?:<[^{]*?>)?\s+(?P<n>[^{]+?)\s*(?:where\b[^{]*)?\{?\s*$"), True, False),
    ("mod", _c(r"^\s*" + RUST_VIS + r"mod\s+(?P<n>\w+)\s*\{"), True, False),
    ("mod", _c(r"^\s*" + RUST_VIS + r"mod\s+(?P<n>\w+)\s*;"), False, False),
    ("macro", _c(r"^\s*macro_rules!\s*(?P<n>\w+)"), False, False),
]

JAVA = [
    ("class", _c(r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*" + MOD_JAVA + r"(?P<kw>class|interface|enum|record|@interface)\s+(?P<n>\w+)"), True, False),
    ("method", _c(r"^\s+(?:@\w+(?:\([^)]*\))?\s+)*" + MOD_JAVA + r"(?:<[^>]+>\s+)?[\w<>\[\],.?]+(?:\s*<[^>]*>)?(?:\[\])*\s+(?P<n>\w+)\s*\([^;=]*$"), False, True),
    ("method", _c(r"^\s+(?:@\w+(?:\([^)]*\))?\s+)*" + MOD_JAVA + r"(?:<[^>]+>\s+)?[\w<>\[\],.?]+(?:\s*<[^>]*>)?(?:\[\])*\s+(?P<n>\w+)\s*\([^=]*\)\s*(?:throws\s+[\w.,\s]+)?;\s*$"), False, True),
    ("ctor", _c(r"^\s+(?:public|private|protected)\s+(?P<n>[A-Z]\w*)\s*\("), False, True),
]

CSHARP = [
    ("ns", _c(r"^\s*namespace\s+(?P<n>[\w.]+)"), True, False),
    ("class", _c(r"^\s*(?:\[[^\]]*\]\s*)*" + MOD_JAVA + r"(?P<kw>class|interface|enum|struct|record)(?:\s+struct|\s+class)?\s+(?P<n>\w+)"), True, False),
    ("method", _c(r"^\s+(?:\[[^\]]*\]\s*)*" + MOD_JAVA + r"[\w<>\[\],.?()]+(?:\s*<[^>]*>)?\s+(?P<n>\w+)\s*(?:<[^>]*>)?\s*\([^;=]*$"), False, True),
    ("method", _c(r"^\s+(?:\[[^\]]*\]\s*)*" + MOD_JAVA + r"[\w<>\[\],.?()]+\s+(?P<n>\w+)\s*(?:<[^>]*>)?\s*\([^=]*\)\s*(?:=>.*)?;\s*$"), False, True),
    ("ctor", _c(r"^\s+(?:public|private|protected|internal)\s+(?P<n>[A-Z]\w*)\s*\("), False, True),
]

KOTLIN = [
    ("class", _c(r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*(?:(?:public|private|protected|internal|open|abstract|sealed|data|enum|inner|value|annotation|companion|expect|actual|final)\s+)*(?P<kw>class|interface|object)\s+(?P<n>\w+)"), True, False),
    ("fn", _c(r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*(?:(?:public|private|protected|internal|open|abstract|override|suspend|inline|operator|infix|tailrec|external|expect|actual|final)\s+)*fun\s+(?:<[^>]+>\s+)?(?:[\w.<>?]+\.)?(?P<n>\w+)\s*\("), False, False),
    ("type", _c(r"^\s*typealias\s+(?P<n>\w+)"), False, False),
]

SWIFT = [
    ("class", _c(r"^\s*(?:@\w+\s+)*(?:(?:public|private|fileprivate|internal|open|final|indirect)\s+)*(?P<kw>class|struct|enum|protocol|actor|extension)\s+(?P<n>[\w.]+)"), True, False),
    ("fn", _c(r"^\s*(?:@\w+\s+)*(?:(?:public|private|fileprivate|internal|open|final|static|class|override|mutating|nonmutating|convenience|required)\s+)*func\s+(?P<n>[\w]+|[^\s(]+)"), False, False),
    ("ctor", _c(r"^\s+(?:(?:public|private|internal|convenience|required|override)\s+)*init[?!]?\s*\("), False, True),
]

DART = [
    ("class", _c(r"^\s*(?:abstract\s+|base\s+|final\s+|sealed\s+|interface\s+|mixin\s+)*(?P<kw>class|mixin|extension|enum)\s+(?P<n>\w+)"), True, False),
    ("fn", _c(r"^(?:[\w<>?,\[\]]+\s+)+(?P<n>\w+)\s*\([^;]*$"), False, False),
    ("method", _c(r"^\s+(?:(?:static|final|const|external|factory|@override)\s+)*(?:[\w<>?,\[\]]+\s+)?(?P<n>[\w.]+)\s*\([^;=]*$"), False, True),
]

C_CPP = [
    ("ns", _c(r"^\s*namespace\s+(?P<n>[\w:]+)\s*\{?\s*$"), True, False),
    ("class", _c(r"^\s*(?:template\s*<[^>]*>\s*)?(?:typedef\s+)?(?P<kw>struct|class|union|enum)(?:\s+class)?\s+(?:\w+\s+)*?(?P<n>\w+)\s*(?:final\s*)?(?::[^{;]*)?\{?\s*$"), True, False),
    ("fn", _c(r"^(?!\s)(?!(?:return|else|if|while|for|switch|case|goto|typedef|using|namespace|template)\b)(?:[\w:*&<>,\[\]]+\s+)+[*&]*(?P<n>[\w:~]+(?:operator\S*)?)\s*\([^;]*$"), False, False),
    ("fn", _c(r"^(?!\s)(?!(?:return|else|typedef|using)\b)(?:extern\s+)?(?:[\w:*&<>,\[\]]+\s+)+[*&]*(?P<n>\w+)\s*\([^;{}=]*\)\s*;\s*$"), False, False),
    ("method", _c(r"^\s+(?:(?:virtual|static|inline|explicit|constexpr|friend|override)\s+)*(?:[\w:*&<>,\[\]]+\s+)*[*&~]*(?P<n>~?\w+)\s*\([^;{}]*\)\s*(?:const\s*)?(?:noexcept\s*)?(?:override\s*)?(?:=\s*(?:0|default|delete)\s*)?[;{]?\s*$"), False, True),
    ("macro", _c(r"^\s*#\s*define\s+(?P<n>\w+)\("), False, False),
]

PHP = [
    ("ns", _c(r"^\s*namespace\s+(?P<n>[\w\\]+)\s*\{"), True, False),
    ("class", _c(r"^\s*(?:(?:abstract|final|readonly)\s+)*(?P<kw>class|interface|trait|enum)\s+(?P<n>\w+)"), True, False),
    ("fn", _c(r"^\s*(?:(?:public|private|protected|static|abstract|final)\s+)*function\s+&?(?P<n>\w+)"), False, False),
]

RUBY = [
    ("class", _c(r"^\s*(?P<kw>class|module)\s+(?P<n>[\w:]+)"), True, False),
    ("fn", _c(r"^\s*def\s+(?P<n>(?:self\.)?[\w?!=\[\]<>+\-*/%]+)"), False, False),
]

SCALA = [
    ("class", _c(r"^\s*(?:(?:abstract|final|sealed|implicit|case|private|protected|open)\s+)*(?P<kw>class|object|trait|enum)\s+(?P<n>\w+)"), True, False),
    ("fn", _c(r"^\s*(?:(?:override|private|protected|final|implicit|inline)\s+)*def\s+(?P<n>[\w$]+)"), False, False),
]

ELIXIR = [
    ("mod", _c(r"^\s*defmodule\s+(?P<n>[\w.]+)"), True, False),
    ("fn", _c(r"^\s*(?:def|defp|defmacro|defmacrop|defguard)\s+(?P<n>[\w?!]+)"), False, False),
]

LUA = [("fn", _c(r"^\s*(?:local\s+)?function\s+(?P<n>[\w.:]+)"), False, False),
       ("fn", _c(r"^\s*(?:local\s+)?(?P<n>[\w.]+)\s*=\s*function\b"), False, False)]
SHELL = [("fn", _c(r"^\s*(?:function\s+)?(?P<n>[\w.:-]+)\s*\(\)\s*\{?"), False, False),
         ("fn", _c(r"^\s*function\s+(?P<n>[\w.:-]+)"), False, False)]
PWSH = [("fn", _c(r"^\s*function\s+(?P<n>[\w-]+)", re.I), False, False),
        ("class", _c(r"^\s*class\s+(?P<n>\w+)", re.I), True, False)]
PERL = [("fn", _c(r"^\s*sub\s+(?P<n>\w+)"), False, False),
        ("mod", _c(r"^\s*package\s+(?P<n>[\w:]+)"), False, False)]
R_LANG = [("fn", _c(r"^(?P<n>[\w.]+)\s*(?:<-|=)\s*function\b"), False, False)]
JULIA = [("fn", _c(r"^\s*function\s+(?P<n>[\w.!]+)"), False, False),
         ("struct", _c(r"^\s*(?:mutable\s+)?struct\s+(?P<n>\w+)"), False, False),
         ("mod", _c(r"^\s*module\s+(?P<n>\w+)"), False, False)]
ZIG = [("fn", _c(r"^\s*(?:pub\s+)?(?:export\s+)?fn\s+(?P<n>\w+)"), False, False),
       ("type", _c(r"^\s*(?:pub\s+)?const\s+(?P<n>\w+)\s*=\s*(?:packed\s+|extern\s+)?(?:struct|enum|union)\b"), False, False)]
HASKELL = [("fn", _c(r"^(?P<n>[a-z_][\w']*)\s*::"), False, False),
           ("type", _c(r"^(?:data|newtype|type|class)\s+(?P<n>[A-Z]\w*)"), False, False)]
OCAML = [("fn", _c(r"^\s*let\s+(?:rec\s+)?(?P<n>[a-z_][\w']*)"), False, False),
         ("type", _c(r"^\s*type\s+(?P<n>[a-z_][\w']*)"), False, False),
         ("mod", _c(r"^\s*module\s+(?P<n>[A-Z]\w*)"), False, False)]
CLOJURE = [("fn", _c(r"^\s*\((?:defn-?|defmacro|defmulti|defprotocol|defrecord|deftype)\s+(?P<n>[^\s()]+)"), False, False)]
SQL = [("table", _c(r"^\s*create\s+(?:or\s+replace\s+)?(?:temporary\s+|temp\s+|unique\s+|materialized\s+)*(?:table|view|function|procedure|index|trigger|type|sequence|schema)\s+(?:if\s+not\s+exists\s+)?(?P<n>[\w.\"`\[\]]+)", re.I), False, False)]
PROTO = [("msg", _c(r"^\s*(?:message|service|enum)\s+(?P<n>\w+)"), True, False),
         ("rpc", _c(r"^\s*rpc\s+(?P<n>\w+)"), False, False)]
GRAPHQL = [("type", _c(r"^\s*(?:extend\s+)?(?:type|interface|enum|input|union|scalar|schema|fragment|query|mutation|subscription)\s+(?P<n>\w+)"), False, False)]
TF = [("res", _c(r"^\s*(?P<n>(?:resource|data|module|variable|output|provider)\s+\"[^\"]+\"(?:\s+\"[^\"]+\")?)"), False, False)]
MD = [("h", _c(r"^(?P<n>#{1,2}\s+\S.*?)\s*#*\s*$"), False, False)]
MAKE = [("target", _c(r"^(?P<n>[\w./%-][\w./%\s-]*?)\s*:(?!=)"), False, False)]
DOCKER = [("stage", _c(r"^\s*FROM\s+\S+\s+AS\s+(?P<n>\w+)", re.I), False, False)]

EXT = {}
for _exts, _spec in [
    ("js jsx mjs cjs ts tsx mts cts vue svelte astro", JS),
    ("py pyi pyw", PY), ("go", GO), ("rs", RUST), ("java", JAVA), ("cs", CSHARP),
    ("kt kts", KOTLIN), ("swift", SWIFT), ("dart", DART),
    ("c h cc cpp cxx hpp hh hxx ino m mm cu cuh", C_CPP), ("php", PHP),
    ("rb rake", RUBY), ("scala sc", SCALA), ("ex exs", ELIXIR), ("lua", LUA),
    ("sh bash zsh fish", SHELL), ("ps1 psm1", PWSH), ("pl pm", PERL), ("r", R_LANG),
    ("jl", JULIA), ("zig", ZIG), ("hs", HASKELL), ("ml mli", OCAML),
    ("clj cljs cljc edn", CLOJURE), ("sql", SQL), ("proto", PROTO),
    ("graphql gql", GRAPHQL), ("tf hcl", TF), ("md mdx markdown", MD),
]:
    for _e in _exts.split():
        EXT[_e] = _spec
NAMED = {"makefile": MAKE, "gnumakefile": MAKE, "dockerfile": DOCKER, "rakefile": RUBY,
         "gemfile": RUBY, "justfile": MAKE}

KIND_PREFIX = {"fn": "", "method": "", "ctor": "", "h": "", "target": "",
               "iface": "iface ", "class": "class ", "type": "type ", "enum": "enum ",
               "ns": "ns ", "struct": "struct ", "trait": "trait ", "impl": "impl ",
               "mod": "mod ", "macro": "macro ", "union": "union ", "const": "const ",
               "table": "", "msg": "", "rpc": "rpc ", "res": "", "stage": "stage ",
               "record": "record ", "object": "object ", "mixin": "mixin ", "ext": "ext ",
               "annot": "@interface ", "proto": "protocol ", "actor": "actor ", "module": "mod "}
KW_KIND = {"class": "class", "interface": "iface", "enum": "enum", "record": "record",
           "@interface": "annot", "struct": "struct", "object": "object", "protocol": "proto",
           "actor": "actor", "extension": "ext", "mixin": "mixin", "union": "union",
           "trait": "trait", "module": "mod"}
MAX_MD_HEADINGS = 10


def spec_for(path):
    base = os.path.basename(path).lower()
    if base in NAMED:
        return NAMED[base]
    if base.startswith("dockerfile"):
        return DOCKER
    ext = base.rsplit(".", 1)[-1] if "." in base else ""
    return EXT.get(ext)


def parse_text(text, spec):
    """Return [[line, kind, name, depth], ...] using an indentation stack."""
    syms, stack = [], []  # stack: (indent, is_container)
    md = spec is MD
    in_fence = False
    for i, raw in enumerate(text.splitlines(), 1):
        if not raw.strip():
            continue
        if md:
            if raw.lstrip().startswith(("```", "~~~")):
                in_fence = not in_fence
            if in_fence:
                continue
        line = raw.expandtabs(4)
        indent = len(line) - len(line.lstrip())
        for kind, rx, container, member_only in spec:
            m = rx.match(line)
            if not m:
                continue
            name = (m.group("n") if "n" in rx.groupindex and m.group("n") else "").strip()
            if kind == "ctor" and not name:
                name = "init"
            if not name or name in KW:
                continue
            while stack and stack[-1][0] >= indent:
                stack.pop()
            parent_ok = not stack or stack[-1][1]
            if not parent_ok:
                break  # nested inside a function body: ignore
            if member_only and not stack:
                continue
            if "recv" in rx.groupindex and m.group("recv"):
                recv = re.sub(r"[*\[\]]|\bmut\b", " ", m.group("recv")).split()
                if recv:
                    name = recv[-1].split("[")[0] + "." + name
            if "kw" in rx.groupindex and m.group("kw"):
                kind = KW_KIND.get(m.group("kw"), kind)
            if kind == "impl":
                name = re.sub(r"\s+", " ", name)
                prev = None
                while prev != name:  # drop generics: impl<T> Foo<'a, T> -> impl Foo
                    prev, name = name, re.sub(r"<[^<>]*>", "", name)
                name = name.strip()[:60]
            if kind == "h":
                name = name[:70]
            syms.append([i, kind, name, len(stack)])
            stack.append((indent, container))
            break
    if md and len(syms) > MAX_MD_HEADINGS:
        syms = syms[:MAX_MD_HEADINGS]
    return syms


# ---------------------------------------------------------------- files


def run_git(root, *args):
    try:
        r = subprocess.run(["git", "-C", root] + list(args), stdout=subprocess.PIPE,
                           stderr=subprocess.DEVNULL, timeout=60)
        return r.stdout if r.returncode == 0 else None
    except (OSError, subprocess.SubprocessError):
        return None


def find_root(start):
    out = run_git(start, "rev-parse", "--show-toplevel")
    if out:
        return out.decode("utf-8", "replace").strip()
    return os.path.abspath(start)


def skip_path(rel, dirs):
    parts = rel.split("/")
    if any(p in dirs for p in parts[:-1]):
        return True
    base = parts[-1]
    low = base.lower()
    return base in SKIP_FILES or low.endswith(SKIP_SUFFIXES)


def list_files(root):
    out = run_git(root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
    if out is not None:
        rels = [p for p in out.decode("utf-8", "surrogateescape").split("\0") if p]
        rels = sorted(set(p for p in rels if not skip_path(p, SKIP_DIRS_ALWAYS)))
        return [p for p in rels if os.path.isfile(os.path.join(root, p))]
    home = os.path.abspath(os.path.expanduser("~"))
    if os.path.abspath(root) in (home, os.path.abspath(os.sep)):
        raise SystemExit("repomap: %s is not a git repo and looks like a home/root folder; "
                         "run it inside a project or pass --root PROJECT" % root)
    rels = []
    for d, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(x for x in dirnames if x not in SKIP_DIRS_WALK and not x.startswith("."))
        for f in filenames:
            rel = os.path.relpath(os.path.join(d, f), root).replace(os.sep, "/")
            if not skip_path(rel, SKIP_DIRS_WALK):
                rels.append(rel)
        if len(rels) > MAX_WALK_FILES:
            raise SystemExit("repomap: more than %d files under %s and no git repo; "
                             "run it inside a project or pass --root PROJECT" % (MAX_WALK_FILES, root))
    return sorted(rels)


def ext_of(rel):
    base = rel.rsplit("/", 1)[-1].lower()
    return base.rsplit(".", 1)[-1] if "." in base else ""


def analyze(root, rel):
    """-> dict(k=kind, l=lines, sym=[...]) ; k in src|other|asset|big"""
    path = os.path.join(root, rel)
    if ext_of(rel) in ASSET_EXT:
        return {"k": "asset", "l": 0, "sym": []}
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as fh:
            data = fh.read(MAX_PARSE_BYTES + 1)
    except OSError:
        return None
    if b"\0" in data[:8192]:
        return {"k": "asset", "l": 0, "sym": []}
    if size > MAX_PARSE_BYTES:
        return {"k": "big", "l": 0, "sym": [], "b": size}
    text = data.decode("utf-8", "replace")
    lines = text.count("\n") + (1 if text and not text.endswith("\n") else 0)
    spec = spec_for(rel)
    if spec is None:
        return {"k": "other", "l": lines, "sym": []}
    # minified / generated one-liners: huge average line length
    if lines and len(text) / lines > 400:
        return {"k": "other", "l": lines, "sym": []}
    return {"k": "src", "l": lines, "sym": parse_text(text, spec)}


# ---------------------------------------------------------------- cache


def paths(root):
    d = os.path.join(root, MAP_DIR)
    return d, os.path.join(d, "cache.json"), os.path.join(d, "MAP.md")


def ensure_dir(root):
    d = os.path.join(root, MAP_DIR)
    os.makedirs(d, exist_ok=True)
    gi = os.path.join(d, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write(GITIGNORE)
    return d


def load_cache(root):
    _, cache_path, _ = paths(root)
    try:
        with open(cache_path, encoding="utf-8") as fh:
            c = json.load(fh)
        if c.get("version") == VERSION:
            return c
    except (OSError, ValueError):
        pass
    return {"version": VERSION, "files": {}}


def stat_key(root, rel):
    try:
        st = os.stat(os.path.join(root, rel))
        return [st.st_mtime_ns, st.st_size]
    except OSError:
        return None


def diff_state(root, cache):
    files = list_files(root)
    old = cache.get("files", {})
    added, modified, same = [], [], []
    stats = {}
    for rel in files:
        key = stat_key(root, rel)
        if key is None:
            continue
        stats[rel] = key
        if rel not in old:
            added.append(rel)
        elif old[rel].get("st") != key:
            modified.append(rel)
        else:
            same.append(rel)
    removed = sorted(set(old) - set(stats))
    return stats, added, modified, removed


def head_sha(root):
    out = run_git(root, "rev-parse", "--short", "HEAD")
    return out.decode().strip() if out else "-"


def build(root, quiet=False):
    t0 = time.time()
    ensure_dir(root)
    cache = load_cache(root)
    stats, added, modified, removed = diff_state(root, cache)
    files = cache.get("files", {})
    for rel in removed:
        files.pop(rel, None)
    for rel in added + modified:
        info = analyze(root, rel)
        if info is None:
            files.pop(rel, None)
            continue
        info["st"] = stats[rel]
        files[rel] = info
    cache["files"] = files
    cache["head"] = head_sha(root)
    cache["built"] = time.strftime("%Y-%m-%d %H:%M")
    text = render_map(root, cache)
    d, cache_path, map_path = paths(root)
    with open(cache_path, "w", encoding="utf-8") as fh:
        json.dump(cache, fh, separators=(",", ":"))
    with open(map_path, "w", encoding="utf-8") as fh:
        fh.write(text)
    nsym = sum(len(f["sym"]) for f in files.values())
    kb = len(text.encode("utf-8")) / 1024
    msg = ("repomap: %d files, %d symbols | re-parsed %d, removed %d | %s/MAP.md %.1f KB (~%dk tokens, %d lines) | %.2fs"
           % (len(files), nsym, len(added) + len(modified), len(removed), MAP_DIR, kb,
              max(1, round(kb * 1024 / 4 / 1000)), text.count("\n"), time.time() - t0))
    if not quiet or added or modified or removed:
        print(msg)
    return cache


def fresh_cache(root):
    """Load cache, rebuilding silently if anything changed."""
    cache = load_cache(root)
    _, added, modified, removed = diff_state(root, cache)
    if added or modified or removed or not cache.get("files"):
        cache = build(root, quiet=True)
    return cache


# ---------------------------------------------------------------- rendering


def to_tree(syms):
    """Flat [line, kind, name, depth] list -> nested [(sym, children)]."""
    root = []
    stack = [(-1, root)]
    for s in syms:
        while stack[-1][0] >= s[3]:
            stack.pop()
        node = (s, [])
        stack[-1][1].append(node)
        stack.append((s[3], node[1]))
    return root


def regroup(tree):
    """Attach top-level `Type.method` / `Type::method` (Go receivers, JS `app.use =`,
    C++ out-of-class definitions) to their type, or to a pseudo group `app.{...}`."""
    by_name = {n[0][2]: n for n in tree if "." not in n[0][2] and "::" not in n[0][2]}
    out, pseudo = [], {}
    for node in tree:
        s, kids = node
        sep = "::" if "::" in s[2] else "."
        pre, _, rest = s[2].rpartition(sep)
        if not pre or not rest or s[1] in ("h", "impl", "res", "table", "target"):
            out.append(node)
            continue
        child = ([s[0], s[1], rest, s[3] + 1], kids)
        if pre in by_name and by_name[pre] is not node:
            by_name[pre][1].append(child)
            continue
        if pre not in pseudo:
            pseudo[pre] = ([s[0], "grp", pre + sep, s[3]], [])
            out.append(pseudo[pre])
        pseudo[pre][1].append(child)
    for node in out:
        node[1].sort(key=lambda n: n[0][0])
    return out


def merge_overloads(nodes):
    """name:10 name:20 (same kind, no members) -> name:10,20"""
    out = []
    for s, kids in nodes:
        if out and not kids and not out[-1][1] and out[-1][0][2] == s[2] and out[-1][0][1] == s[1]:
            out[-1][0].append(s[0])
            continue
        out.append((list(s[:4]), kids))
    return out


def fmt_syms(syms, limit=MAX_SYMS_PER_FILE):
    """Compact form: class Router:40{get:52 post:70} · handleError:180"""
    shown = [0]

    def render(nodes, top):
        parts = []
        nodes = merge_overloads(nodes)
        for i, (s, kids) in enumerate(nodes):
            if shown[0] >= limit or (not top and i >= MAX_CHILDREN):
                if not top:
                    parts.append("+%d" % (len(nodes) - i))
                break
            shown[0] += 1
            if s[1] == "grp":
                text = s[2]
            else:
                text = "%s%s:%s" % (KIND_PREFIX.get(s[1], s[1] + " "), s[2],
                                    ",".join(str(x) for x in [s[0]] + s[4:]))
            if kids:
                inner = render(kids, False)
                if inner:
                    text += "{" + " ".join(inner) + "}"
            parts.append(text)
        return parts

    text = " · ".join(render(regroup(to_tree(syms)), True))
    rest = len(syms) - shown[0]
    if shown[0] >= limit and rest > 0:
        text += " · +%d more (outline)" % rest
    return text


TEST_RX = re.compile(r"(^|/)(tests?|__tests__|specs?|e2e|fixtures?|testdata)/|(^|/)test_[^/]+$"
                     r"|_(test|spec)\.[^/.]+$|[.-](test|spec)s?\.[^/]+$|Tests?\.(java|kt|cs|swift|scala|php)$")


def is_test(rel):
    return bool(TEST_RX.search(rel))


def dir_of(rel):
    return rel.rsplit("/", 1)[0] + "/" if "/" in rel else "./"


def render_index(files):
    dirs = {}
    for rel, f in files.items():
        dirs.setdefault(dir_of(rel), []).append((rel, f))
    depth = max((d.count("/") for d in dirs), default=1)
    while depth > 1:
        prefixes = {"/".join(d.split("/")[:depth]) for d in dirs}
        if len(prefixes) <= INDEX_MAX_ENTRIES:
            break
        depth -= 1
    agg = {}
    for d, items in dirs.items():
        key = d if d == "./" else "/".join(d.rstrip("/").split("/")[:depth]) + "/"
        a = agg.setdefault(key, {"files": 0, "syms": 0, "lines": 0, "ext": {}})
        for rel, f in items:
            a["files"] += 1
            a["syms"] += len(f["sym"])
            a["lines"] += f.get("l", 0)
            if f["k"] in ("src", "other"):
                e = ext_of(rel) or rel.rsplit("/", 1)[-1]
                a["ext"][e] = a["ext"].get(e, 0) + 1
    rows = []
    for key in sorted(agg):
        a = agg[key]
        exts = ",".join(e for e, _ in sorted(a["ext"].items(), key=lambda x: -x[1])[:4])
        rows.append("- `%s` %d files, %d lines, %d symbols%s"
                    % (key, a["files"], a["lines"], a["syms"], (" (" + exts + ")") if exts else ""))
    return rows


def render_files(files, prefix=""):
    by_dir = {}
    for rel in sorted(files):
        if prefix and not (rel == prefix or rel.startswith(prefix.rstrip("/") + "/") or rel.startswith(prefix)):
            continue
        by_dir.setdefault(dir_of(rel), []).append(rel)
    out = []
    for d in sorted(by_dir):
        out.append("\n### %s" % d)
        others, assets = [], 0
        for rel in by_dir[d]:
            f = files[rel]
            base = rel.rsplit("/", 1)[-1]
            if f["k"] == "asset":
                assets += 1
            elif f["k"] == "big":
                out.append("%s (%.1f MB, not parsed)" % (base, f.get("b", 0) / 1e6))
            elif f["sym"] and is_test(rel):
                out.append("%s %dL [test, %d symbols: outline to list]" % (base, f["l"], len(f["sym"])))
            elif f["sym"]:
                out.append("%s %dL: %s" % (base, f["l"], fmt_syms(f["sym"])))
            elif f["k"] == "src" and f["l"] > 60:
                out.append("%s %dL" % (base, f["l"]))
            else:
                others.append(base)
        if others:
            extra = len(others) - MAX_OTHER_NAMES
            out.append("other: " + ", ".join(others[:MAX_OTHER_NAMES]) + (" +%d" % extra if extra > 0 else ""))
        if assets:
            out.append("assets: %d" % assets)
    return out


def render_map(root, cache):
    files = cache["files"]
    nsym = sum(len(f["sym"]) for f in files.values())
    lines = [
        "# Code map: %s (%d files, %d symbols)" % (os.path.basename(root.rstrip("/\\")) or root, len(files), nsym),
        "Generated by repomap.py at %s, git %s. Do not edit. `name:N` = defined at line N; `{...}` = members." % (cache.get("built", "?"), cache.get("head", "-")),
        "Refresh: `repomap.py build` · lookup: `repomap.py find NAME` · one dir: `repomap.py show DIR/`",
        "",
        "## Directory index",
    ]
    lines += render_index(files)
    lines += ["", "## Files"]
    lines += render_files(files)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- commands


def cmd_status(root):
    cache = load_cache(root)
    if not cache.get("files"):
        print("repomap: no map yet -> run `repomap.py build`")
        return 1
    _, added, modified, removed = diff_state(root, cache)
    if not (added or modified or removed):
        print("repomap: up to date (built %s, git %s; now %s)" % (cache.get("built"), cache.get("head"), head_sha(root)))
        return 0
    print("repomap: stale since %s (git %s -> %s)" % (cache.get("built"), cache.get("head"), head_sha(root)))
    for label, items in (("modified", modified), ("added", added), ("removed", removed)):
        if items:
            shown = items[:30]
            print("%s (%d): %s%s" % (label, len(items), " ".join(shown), " ..." if len(items) > 30 else ""))
    print("-> only these files may need re-reading; run `repomap.py build` to refresh the map")
    return 0


def cmd_find(root, pattern, limit):
    cache = fresh_cache(root)
    try:
        rx = re.compile(pattern, re.I)
    except re.error:
        rx = re.compile(re.escape(pattern), re.I)
    hits = []
    for rel in sorted(cache["files"]):
        syms = cache["files"][rel]["sym"]
        parents = []
        for s in syms:
            del parents[s[3]:]
            bare = re.split(r"\.|::", s[2])[-1]
            if rx.search(s[2]) or rx.search(bare):
                owner = ".".join(p for p in parents if p)
                full = (owner + "." if owner else "") + s[2]
                exact = pattern.lower() in (s[2].lower(), bare.lower())
                hits.append((0 if exact else 1, "%s:%d %s %s" % (rel, s[0], s[1], full)))
            parents.append(s[2] if s[1] in ("class", "struct", "trait", "impl", "ns", "mod", "iface", "msg") else "")
    hits.sort(key=lambda h: h[0])
    for _, h in hits[:limit]:
        print(h)
    if len(hits) > limit:
        print("... %d more (narrow the pattern or use -n)" % (len(hits) - limit))
    if not hits:
        print("no symbol matches %r -> try `rg -n %s`" % (pattern, pattern))
    return 0 if hits else 1


def cmd_outline(root, targets):
    rc = 0
    for t in targets:
        path = t if os.path.isabs(t) else os.path.join(os.getcwd(), t)
        if not os.path.isfile(path):
            print("%s: not found" % t)
            rc = 1
            continue
        spec = spec_for(path)
        try:
            with open(path, "rb") as fh:
                text = fh.read().decode("utf-8", "replace")
        except OSError as e:
            print("%s: %s" % (t, e))
            rc = 1
            continue
        n = text.count("\n") + (1 if text and not text.endswith("\n") else 0)
        if spec is None:
            print("%s (%d lines): no outline support for this file type" % (t, n))
            continue
        syms = parse_text(text, spec)
        if spec is MD:  # outline shows all headings, not just the capped map view
            syms = [[i, "h", ln.strip()[:90], 0] for i, ln in enumerate(text.splitlines(), 1)
                    if re.match(r"^#{1,4}\s+\S", ln)]
        print("%s (%d lines, %d symbols)" % (t, n, len(syms)))
        for s in syms:
            print("%s%5d %s%s" % ("  " * s[3], s[0], KIND_PREFIX.get(s[1], s[1] + " "), s[2]))
    return rc


def cmd_show(root, prefix):
    cache = fresh_cache(root)
    rel = prefix.replace("\\", "/")
    if os.path.isabs(rel):
        rel = os.path.relpath(rel, root).replace(os.sep, "/")
    rel = rel[2:] if rel.startswith("./") else rel
    if rel in (".", "./"):
        rel = ""
    out = render_files(cache["files"], rel)
    if not out:
        print("nothing under %r in the map" % prefix)
        return 1
    print("\n".join(out).lstrip("\n"))
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="repomap.py", description=__doc__.split("\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", help="repository root (default: git top-level or cwd)")
    sub = ap.add_subparsers(dest="cmd")
    b = sub.add_parser("build", help="refresh the map (incremental)")
    b.add_argument("--quiet", action="store_true", help="print nothing when already up to date")
    sub.add_parser("status", help="what changed since the last build")
    f = sub.add_parser("find", help="find symbol definitions by regex")
    f.add_argument("pattern")
    f.add_argument("-n", type=int, default=30, help="max results (default 30)")
    o = sub.add_parser("outline", help="symbols of one or more files")
    o.add_argument("files", nargs="+")
    s = sub.add_parser("show", help="map lines for a directory or file prefix")
    s.add_argument("prefix")
    args = ap.parse_args(argv)
    root = find_root(args.root or os.getcwd())
    cmd = args.cmd or "build"
    if cmd == "build":
        build(root, quiet=getattr(args, "quiet", False))
        return 0
    if cmd == "status":
        return cmd_status(root)
    if cmd == "find":
        return cmd_find(root, args.pattern, args.n)
    if cmd == "outline":
        return cmd_outline(root, args.files)
    if cmd == "show":
        return cmd_show(root, args.prefix)
    ap.print_help()
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except BrokenPipeError:
        sys.exit(0)
