#!/usr/bin/env python3
"""quiet_run - run a noisy command, keep the full log on disk, print only what matters.

  quiet_run.py [options] -- <command> [args...]
  quiet_run.py [options] --shell "cmd | with && shell syntax"

Prints one status line (exit code, duration, log size), then the problem lines
(errors / failures / tracebacks with a little context) and the tail, capped at
--lines. The full output is saved to .codemap/logs/last.log (previous run:
prev.log) so you can grep it instead of re-running. Exits with the command's
exit code. Python 3.8+, standard library only.
"""

import argparse
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
from collections import deque

GITIGNORE = ("# generated by repomap: keep NOTES.md in git; other state stays local\n"
             "*\n!.gitignore\n!NOTES.md\n")
ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b\][^\x07]*\x07|\x1b[()][A-Z0-9]")
PROBLEM = re.compile(
    r"error|fail(?:ed|ure|ing|s)?\b|exception|traceback|panic|fatal|assert|"
    r"\bE\s{2,}|✗|✘|✖|FAIL|ERR!|undefined reference|cannot find|not found|"
    r"no such file|segmentation fault|core dumped|abort(?:ed)?\b|denied|refused|"
    r"timed? ?out|unresolved|mismatch|expected .* (?:got|but|to)|unexpected",
    re.I)
WARNING = re.compile(r"warn(?:ing)?\b|deprecat", re.I)
NOISE = re.compile(
    r"\b0 (?:errors?|failures?|failed|fail|problems?)\b|\b(?:errors?|failures?|failed|fail)[:=] ?0\b|"
    r"\bno (?:errors?|failures?|problems?)\b|^\s*(?:PASS|ok|✓|✔|√)\b|\bPASSED\b|-Werror|"
    r"--no-?fail|fail-fast|failfast",
    re.I)
PASS_LINE = re.compile(r"^\s*(?:PASS|ok|✓|✔|√)\b|\bPASSED\b|\.\.\. ?ok$|^\s*\.+\s*$", re.I)
MAX_LINE = 300


def repo_root():
    try:
        r = subprocess.run(["git", "rev-parse", "--show-toplevel"], stdout=subprocess.PIPE,
                           stderr=subprocess.DEVNULL, timeout=20)
        if r.returncode == 0:
            return r.stdout.decode("utf-8", "replace").strip()
    except (OSError, subprocess.SubprocessError):
        pass
    return os.getcwd()


def default_log():
    d = os.path.join(repo_root(), ".codemap")
    for path in (d, os.path.join(d, "logs"), os.path.join(d, ".gitignore")):
        if os.path.islink(path):
            raise ValueError("symlink state paths are refused")
    os.makedirs(os.path.join(d, "logs"), exist_ok=True)
    gi = os.path.join(d, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write(GITIGNORE)
    return os.path.join(d, "logs", "last.log")


def clean(raw):
    out = []
    for line in raw.splitlines():
        line = ANSI.sub("", line)
        if "\r" in line:  # progress bars: keep the final state
            line = line.rstrip("\r").split("\r")[-1]
        line = line.rstrip()
        if len(line) > MAX_LINE:
            line = line[:MAX_LINE] + " …[+%d chars]" % (len(line) - MAX_LINE)
        out.append(line)
    return out


def collapse(lines):
    """Consecutive identical lines -> one line with an (xN) marker."""
    out = []
    for line in lines:
        if out and line == out[-1][0]:
            out[-1][1] += 1
            continue
        out.append([line, 1])
    return ["%s  (x%d)" % (l, n) if n > 1 and l.strip() else l for l, n in out]


def pick(lines, rc, max_lines, tail_n, ctx, warnings):
    n = len(lines)
    is_hit = [bool(PROBLEM.search(l) or (warnings and WARNING.search(l))) and not NOISE.search(l)
              for l in lines]
    hits = [i for i, h in enumerate(is_hit) if h]
    tail = pick_tail(lines, tail_n)
    tail_start = tail[0] if tail else n
    if rc == 0 and not hits:
        return [], tail, 0
    budget = max(5, max_lines - len(tail))
    chosen, used, skipped = [], set(), 0
    for i in hits:
        if i >= tail_start:
            continue
        window = [j for j in range(max(0, i - ctx), min(tail_start, i + ctx + 2))
                  if j not in used and not PASS_LINE.search(lines[j])]
        if len(chosen) + len(window) > budget:
            skipped += 1
            continue
        chosen.extend(window)
        used.update(window)
    return sorted(chosen), tail, skipped


def pick_tail(lines, tail_n):
    """Last tail_n lines, skipping per-test 'PASSED/ok' chatter (the final 3 lines always kept)."""
    n = len(lines)
    keep = []
    for i in range(n - 1, max(-1, n - 400), -1):
        if len(keep) >= tail_n:
            break
        if i >= n - 3 or not PASS_LINE.search(lines[i]):
            keep.append(i)
    return sorted(keep)


def build_cmd(args):
    if args.shell:
        return args.shell, True
    cmd = args.cmd
    if cmd and cmd[0] == "--":
        cmd = cmd[1:]
    if not cmd:
        return None, False
    exe = shutil.which(cmd[0])
    return ([exe] + cmd[1:]) if exe else cmd, False


def positive(value):
    value = float(value)
    if value <= 0:
        raise argparse.ArgumentTypeError("must be positive")
    return value


def stop_process(proc):
    if os.name == "posix":
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
    elif os.name == "nt":
        subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        proc.kill()


def copy_atomic(source, target):
    directory = os.path.dirname(os.path.abspath(target))
    fd, temporary = tempfile.mkstemp(prefix=".quiet-run-", dir=directory)
    os.close(fd)
    try:
        shutil.copyfile(source, temporary)
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="quiet_run.py", usage="%(prog)s [options] -- command [args...]",
                                 description="Run a command; print only errors + tail; full log to a file.")
    ap.add_argument("--lines", type=int, default=60, help="max output lines (default 60)")
    ap.add_argument("--tail", type=int, default=15, help="tail lines always shown (default 15)")
    ap.add_argument("--context", type=int, default=2, help="context lines around a problem line (default 2)")
    ap.add_argument("--warnings", action="store_true", help="treat warnings as problem lines too")
    ap.add_argument("--timeout", type=positive, default=None, help="stop the process tree after N seconds")
    ap.add_argument("--log", default=None, help="log file (default .codemap/logs/last.log)")
    ap.add_argument("--max-log-bytes", type=int, default=20_000_000, help="disk log cap; output is still drained")
    ap.add_argument("--max-read-bytes", type=int, default=2_000_000, help="bounded head/tail summary read")
    ap.add_argument("--shell", default=None, metavar="CMDLINE", help="run CMDLINE through the shell")
    ap.add_argument("cmd", nargs=argparse.REMAINDER)
    args = ap.parse_args(argv)
    if args.lines < 1 or args.tail < 0 or args.context < 0 or args.max_log_bytes < 1 or args.max_read_bytes < 128:
        ap.error("lines/log bytes must be positive; tail/context nonnegative; read bytes >= 128")
    command, use_shell = build_cmd(args)
    if command is None:
        ap.error("no command given")

    log = os.path.abspath(args.log or default_log())
    os.makedirs(os.path.dirname(log), exist_ok=True)
    # Stable last.log is only published after capture. Concurrent runs have unique logs.
    capture = log if args.log else os.path.join(os.path.dirname(log), "run-%d.log" % time.time_ns())
    if os.path.islink(capture) or os.path.islink(os.path.dirname(capture)):
        ap.error("symlink log destinations are refused")
    try:
        sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../token-saver/scripts")))
        from ts_io import redact
    except ImportError:
        # Legacy single-skill installs retain limited redaction, without extra dependencies.
        def redact(text):
            return re.sub(r"(?i)(Bearer\s+)[A-Za-z0-9._~+/-]{8,}", r"\1[REDACTED]", text)
    env = dict(os.environ, NO_COLOR="1", PYTHONUNBUFFERED="1")
    t0 = time.monotonic()
    timed_out = False
    limited = [False]
    writer_errors = []
    recent = deque(maxlen=200)
    with open(capture, "wb") as fh:
        try:
            proc = subprocess.Popen(command, shell=use_shell, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                    stdin=subprocess.DEVNULL, env=env, start_new_session=(os.name == "posix"))
        except OSError as e:
            print("quiet_run: cannot start command: %s" % e)
            return 127
        def drain():
            written, in_key = 0, False
            try:
                while True:
                    chunk = proc.stdout.readline(65536)
                    if not chunk:
                        break
                    line = chunk.decode("utf-8", "replace")
                    if re.search(r"-----BEGIN .*PRIVATE KEY-----", line):
                        in_key = True
                    if in_key:
                        key_end = bool(re.search(r"-----END .*PRIVATE KEY-----", line))
                        line = "[REDACTED PRIVATE KEY]\n"
                        in_key = not key_end
                    data = redact(line).encode("utf-8")
                    recent.append(redact(line)[:1000].rstrip())
                    remaining = max(0, args.max_log_bytes - written)
                    fh.write(data[:remaining])
                    written += min(len(data), remaining)
                    limited[0] = limited[0] or len(data) > remaining
            except OSError as error:
                writer_errors.append(str(error))
            finally:
                proc.stdout.close()
        reader = threading.Thread(target=drain, daemon=True)
        reader.start()
        try:
            rc = proc.wait(timeout=args.timeout)
        except subprocess.TimeoutExpired:
            stop_process(proc)
            rc = proc.wait()
            timed_out = True
        except KeyboardInterrupt:
            stop_process(proc)
            proc.wait()
            reader.join(timeout=3)
            raise
        reader.join(timeout=5)
        if reader.is_alive():
            stop_process(proc)
            reader.join(timeout=3)
        if reader.is_alive() or writer_errors:
            print("quiet_run: output capture did not finish; inspect %s" % capture)
            return 125
    dt = time.monotonic() - t0
    if not args.log:
        if os.path.exists(log):
            copy_atomic(log, os.path.join(os.path.dirname(log), "prev.log"))
        copy_atomic(capture, log)
        logs = sorted(p for p in os.listdir(os.path.dirname(log)) if re.fullmatch(r"run-\d+\.log", p))
        for old in logs[:-10]:
            try:
                os.unlink(os.path.join(os.path.dirname(log), old))
            except OSError:
                pass
    with open(capture, "rb") as fh:
        if os.path.getsize(capture) <= args.max_read_bytes:
            raw = fh.read(args.max_read_bytes).decode("utf-8", "replace")
        else:
            half = args.max_read_bytes // 2
            head = fh.read(half).decode("utf-8", "replace")
            fh.seek(-half, os.SEEK_END)
            tail_raw = fh.read(half).decode("utf-8", "replace")
            raw = head + "\n[summary omitted middle of log; inspect the file]\n" + tail_raw
    if limited[0]:
        raw += "\n[log cap reached; recent captured tail follows]\n" + "\n".join(recent)
    lines = collapse(clean(raw))
    rel = os.path.relpath(capture)
    status = "TIMEOUT after %.0fs" % dt if timed_out else "exit=%d" % rc
    print("%s · %.1fs · log%s: %s" % (status, dt, " capped" if limited[0] else "", rel))
    if not lines:
        return 124 if timed_out else (128 - rc if rc < 0 else rc)
    remaining = args.lines - 1
    problems, tail, skipped = pick(lines, rc, remaining, min(args.tail, remaining), args.context, args.warnings)
    output = []
    if problems:
        prev = None
        for i in problems:
            if prev is not None and i != prev + 1:
                output.append("  ...")
            output.append(lines[i])
            prev = i
        if skipped:
            output.append("  ... %d more problem spots -> inspect the log" % skipped)
    shown = set(problems)
    tail = [i for i in tail if i not in shown]
    if tail:
        for i in tail:
            output.append(lines[i])
    for line in output[:remaining]:
        print(line)
    return 124 if timed_out else (128 - rc if rc < 0 else rc)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except BrokenPipeError:
        sys.exit(0)
    except (OSError, ValueError) as error:
        print("quiet_run: " + str(error), file=sys.stderr)
        sys.exit(2)
