#!/usr/bin/env python3
"""quiet_run - run a noisy command, keep the full log on disk, print only what matters.

  quiet_run.py [options] -- <command> [args...]
  quiet_run.py [options] --shell "cmd | with && shell syntax"

Prints one status line (exit code, duration, log size), then the problem lines
(errors / failures / tracebacks with a little context) and the tail, capped at
--lines. The full output is saved to .codemap/logs/last.log (previous run:
prev.log) so you can grep it instead of re-running. Exits with the command's
exit code. Python 3.8+, standard library only.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time

GITIGNORE = "# generated by repomap: keep NOTES.md in git, ignore the rest\n*\n!.gitignore\n!NOTES.md\n"
ANSI = re.compile(r"\x1b\[[0-9;?]*[ -/]*[@-~]|\x1b\][^\x07]*\x07|\x1b[()][A-Z0-9]")
PROBLEM = re.compile(
    r"error|fail(?:ed|ure|ing|s)?\b|exception|traceback|panic|fatal|assert|"
    r"\bE\s{2,}|✗|✘|✖|FAIL|ERR!|undefined reference|cannot find|not found|"
    r"no such file|segmentation fault|core dumped|abort(?:ed)?\b|denied|refused|"
    r"timed? ?out|unresolved|mismatch|expected .* (?:got|but|to)|unexpected",
    re.I)
WARNING = re.compile(r"warn(?:ing)?\b|deprecat", re.I)
NOISE = re.compile(
    r"\b0 (?:errors?|failures?|failed|fail|problems?)\b|\b(?:errors?|failures?|failed|fail)[:=] ?0\b|"
    r"\bno (?:errors?|failures?|problems?)\b|^\s*(?:PASS|ok|✓|✔|√)\b|\bPASSED\b|-Werror|"
    r"--no-?fail|fail-fast|failfast",
    re.I)
PASS_LINE = re.compile(r"^\s*(?:PASS|ok|✓|✔|√)\b|\bPASSED\b|\.\.\. ?ok$|^\s*\.+\s*$", re.I)
MAX_LINE = 300


def repo_root():
    try:
        r = subprocess.run(["git", "rev-parse", "--show-toplevel"], stdout=subprocess.PIPE,
                           stderr=subprocess.DEVNULL, timeout=20)
        if r.returncode == 0:
            return r.stdout.decode("utf-8", "replace").strip()
    except (OSError, subprocess.SubprocessError):
        pass
    return os.getcwd()


def default_log():
    d = os.path.join(repo_root(), ".codemap")
    os.makedirs(os.path.join(d, "logs"), exist_ok=True)
    gi = os.path.join(d, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as fh:
            fh.write(GITIGNORE)
    return os.path.join(d, "logs", "last.log")


def clean(raw):
    out = []
    for line in raw.splitlines():
        line = ANSI.sub("", line)
        if "\r" in line:  # progress bars: keep the final state
            line = line.rstrip("\r").split("\r")[-1]
        line = line.rstrip()
        if len(line) > MAX_LINE:
            line = line[:MAX_LINE] + " …[+%d chars]" % (len(line) - MAX_LINE)
        out.append(line)
    return out


def collapse(lines):
    """Consecutive identical lines -> one line with an (xN) marker."""
    out = []
    for line in lines:
        if out and line == out[-1][0]:
            out[-1][1] += 1
            continue
        out.append([line, 1])
    return ["%s  (x%d)" % (l, n) if n > 1 and l.strip() else l for l, n in out]


def pick(lines, rc, max_lines, tail_n, ctx, warnings):
    n = len(lines)
    is_hit = [bool(PROBLEM.search(l) or (warnings and WARNING.search(l))) and not NOISE.search(l)
              for l in lines]
    hits = [i for i, h in enumerate(is_hit) if h]
    tail = pick_tail(lines, tail_n)
    tail_start = tail[0] if tail else n
    if rc == 0 and not hits:
        return [], tail, 0
    budget = max(5, max_lines - len(tail))
    chosen, used, skipped = [], set(), 0
    for i in hits:
        if i >= tail_start:
            continue
        window = [j for j in range(max(0, i - ctx), min(tail_start, i + ctx + 2))
                  if j not in used and not PASS_LINE.search(lines[j])]
        if len(chosen) + len(window) > budget:
            skipped += 1
            continue
        chosen.extend(window)
        used.update(window)
    return sorted(chosen), tail, skipped


def pick_tail(lines, tail_n):
    """Last tail_n lines, skipping per-test 'PASSED/ok' chatter (the final 3 lines always kept)."""
    n = len(lines)
    keep = []
    for i in range(n - 1, max(-1, n - 400), -1):
        if len(keep) >= tail_n:
            break
        if i >= n - 3 or not PASS_LINE.search(lines[i]):
            keep.append(i)
    return sorted(keep)


def build_cmd(args):
    if args.shell:
        return args.shell, True
    cmd = args.cmd
    if cmd and cmd[0] == "--":
        cmd = cmd[1:]
    if not cmd:
        return None, False
    if len(cmd) == 1 and re.search(r"[|&;<>]| \S", cmd[0]):
        return cmd[0], True  # a whole command line passed as one string
    exe = shutil.which(cmd[0])
    if exe is None and os.name == "nt":
        return subprocess.list2cmdline(cmd), True  # npm.cmd, builtins, ...
    return ([exe] + cmd[1:]) if exe else cmd, False


def main(argv=None):
    ap = argparse.ArgumentParser(prog="quiet_run.py", usage="%(prog)s [options] -- command [args...]",
                                 description="Run a command; print only errors + tail; full log to a file.")
    ap.add_argument("--lines", type=int, default=60, help="max output lines (default 60)")
    ap.add_argument("--tail", type=int, default=15, help="tail lines always shown (default 15)")
    ap.add_argument("--context", type=int, default=2, help="context lines around a problem line (default 2)")
    ap.add_argument("--warnings", action="store_true", help="treat warnings as problem lines too")
    ap.add_argument("--timeout", type=float, default=None, help="kill after N seconds")
    ap.add_argument("--log", default=None, help="log file (default .codemap/logs/last.log)")
    ap.add_argument("--shell", default=None, metavar="CMDLINE", help="run CMDLINE through the shell")
    ap.add_argument("cmd", nargs=argparse.REMAINDER)
    args = ap.parse_args(argv)
    command, use_shell = build_cmd(args)
    if command is None:
        ap.error("no command given")

    log = args.log or default_log()
    if os.path.exists(log):
        try:
            os.replace(log, os.path.join(os.path.dirname(log) or ".", "prev.log"))
        except OSError:
            pass
    env = dict(os.environ, NO_COLOR="1", PYTHONUNBUFFERED="1")
    t0 = time.time()
    timed_out = False
    with open(log, "wb") as fh:
        try:
            proc = subprocess.Popen(command, shell=use_shell, stdout=fh, stderr=subprocess.STDOUT,
                                    stdin=subprocess.DEVNULL, env=env)
        except OSError as e:
            print("quiet_run: cannot start %r: %s" % (command, e))
            return 127
        try:
            rc = proc.wait(timeout=args.timeout)
        except subprocess.TimeoutExpired:
            proc.kill()
            rc = proc.wait()
            timed_out = True
        except KeyboardInterrupt:
            proc.kill()
            proc.wait()
            raise
    dt = time.time() - t0

    with open(log, "rb") as fh:
        raw = fh.read().decode("utf-8", "replace")
    lines = collapse(clean(raw))
    rel = os.path.relpath(log)
    if len(rel) > len(log):
        rel = log
    status = "TIMEOUT after %.0fs" % dt if timed_out else "exit=%d" % rc
    print("%s · %.1fs · %d lines · full log: %s" % (status, dt, len(lines), rel))
    if not lines:
        return rc if not timed_out else 124
    problems, tail, skipped = pick(lines, rc, args.lines, args.tail, args.context, args.warnings)
    if problems:
        print("--- problems ---")
        prev = None
        for i in problems:
            if prev is not None and i != prev + 1:
                print("  ...")
            print(lines[i])
            prev = i
        if skipped:
            print("  ... %d more problem spots not shown -> grep the log" % skipped)
    shown = set(problems)
    tail = [i for i in tail if i not in shown]
    if tail:
        if tail[0] > 0:
            print("--- tail ---")
        for i in tail:
            print(lines[i])
    return 124 if timed_out else rc


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except BrokenPipeError:
        sys.exit(0)
